name: 'Push workflow'
run-name: ${{ github.actor }} запушил в ветку ${{ github.ref_name }}

on: [workflow_dispatch, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: 'Install dependencies'
        run: npm ci

      - name: 'Run lint'
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: 'Run tests'
        run: npm test